corpora:
  bnc:
    name:  "BNC"
    path:  "/storage/users/wingfiel/corpora/BNC/2 Tokenised/BNC.corpus"
    index: "/storage/users/wingfiel/indexes/BNC.freqdist"
  subtitles:
    name:  "BBC"
    path:  "/storage/users/wingfiel/corpora/BBC/4 Tokenised/BBC.corpus"
    index: "/storage/users/wingfiel/indexes/BBC.freqdist"
  ukwac:
    name:  "UKWAC"
    path:  "/storage/users/wingfiel/corpora/UKWAC/3 Tokenised/UKWAC.corpus"
    index: "/storage/users/wingfiel/indexes/UKWAC.freqdist"

sensorimotor-norms-location: "/storage/users/wingfiel/experimental_data/FINAL_sensorimotor_norms_for_39707_words.csv"

models:
  directory: "/storage/users/wingfiel/vectors/vocab-evolution/"
graphs_dir: "/storage/users/wingfiel/graphs/vocab-evolution/"

# Notification emails
email_connection_details: "/mmfs1/home/users/wingfiel/notify@cwcomplex.net.txt"

output_dir:             "/mmfs1/scratch/hpc/57/wingfiel/spreading_activation_results/Model output/"
